theme: jekyll-theme-cayman
title: Compositions
description: Selection of my classical music compositions
#repository: https://github.com/your-repo  # Remove or comment out this line
baseurl: "/"  # <-- Ensure this is correct
